### ISSUE TITLE
(suggestion) make a directory with examples

### ISSUE THREAD

**Issue by semenInRussia** [Jobhdez/Yotta#2]
I want to explore this repository, but I do not do it easily, because documentation is not full and examples is missing

**Comment by Jobhdez** [comment]
Ill work on the examples. in the meantime look at the tests.

example: adding a vector to a vector

```
(yotta:generate-lisp 
      (yotta:make-lisp-interlan
	       (yotta:parse-with-lexer
	       (yotta:token-generator
		(yotta:lex-line "[4 5 6] + [5 6 7]"))
	       yotta:*linear-algebra-grammar*)))
```

You can also do:

1. dot product -- ie "[1 2 3] * [5 6 7]"`
2. vector subtraction -- ie "[3 4 5] - [ 6 2 3]"
3. matrix addition -- ie "[[4 5 6] [6 7 8]] + [[4 5 6] [6 7 8]]"
4. matrix subtraction 
5.  compile just a vector or matrix -- ie "[3 4 5]" or "[[5 6 7] [7 8 9]]"

It is a simple language but I have just started like two weeks ago.

`yotta:generate-lisp` is defined in `src/backends/lisp/generatelisp.lisp`

`yotta:parse-with-lexer` is defined in `cl-yacc` which is the parser generator  I am using but since  I am using `cl-yacc` in  my `yotta` package I can call it within yotta.

`yotta:token-generator` is defined in `src/lexer/lexer.lisp`

`yotta:lex-line` is defined in `src/lexer/lexer.lisp`

`yotta:*linear-algebra-grammar*` is the grammar (parser) defined in `src/parser/parser.lisp`

`(token-generator (lex-line <exp>))` tokenizes the expression where <exp> is a string eg "[3 4 5] + [4 5 6]".

`(parse-with-lexer <tokens> *linear-algebra-grammar*)` parses the tokens where <tokens> is the output of `(token-generator (lex-line <exp>))` and *linear-algebra-grammar* is the grammar of the language 

`(make-lisp-interlan <parse-tree>)` constructs the intermediate language from <parse-tree> where <parse-tree> is the output of `parse-with-lexer`.

anyways, I hope this helps. let me know if you have any questions.

**Comment by Jobhdez** [comment]
> I want to explore this repository, but I do not do it easily, because documentation is not full and examples is missing
Ill work on the examples. in the meantime look at the tests.

example: adding a vector to a vector

```
(yotta:generate-lisp 
      (yotta:make-lisp-interlan
	       (yotta:parse-with-lexer
	       (yotta:token-generator
		(yotta:lex-line "[4 5 6] + [5 6 7]"))
	       yotta:*linear-algebra-grammar*)))
```

You can also do:

1. dot product -- ie "[1 2 3] * [5 6 7]"`
2. vector subtraction -- ie "[3 4 5] - [ 6 2 3]"
3. matrix addition -- ie "[[4 5 6] [6 7 8]] + [[4 5 6] [6 7 8]]"
4. matrix subtraction 
5.  compile just a vector or matrix -- ie "[3 4 5]" or "[[5 6 7] [7 8 9]]"

It is a simple language but I have just started like two weeks ago.

`yotta:generate-lisp` is defined in `src/backends/lisp/generatelisp.lisp`

`yotta:parse-with-lexer` is defined in `cl-yacc` which is the parser generator  I am using but since  I am using `cl-yacc` in  my `yotta` package I can call it within yotta.

`yotta:token-generator` is defined in `src/lexer/lexer.lisp`

`yotta:lex-line` is defined in `src/lexer/lexer.lisp`

`yotta:*linear-algebra-grammar*` is the grammar (parser) defined in `src/parser/parser.lisp`

`(token-generator (lex-line <exp>))` tokenizes the expression where <exp> is a string eg "[3 4 5] + [4 5 6]".

`(parse-with-lexer <tokens> *linear-algebra-grammar*)` parses the tokens where <tokens> is the output of `(token-generator (lex-line <exp>))` and *linear-algebra-grammar* is the grammar of the language 

`(make-lisp-interlan <parse-tree>)` constructs the intermediate language from <parse-tree> where <parse-tree> is the output of `parse-with-lexer`.

anyways, I hope this helps. let me know if you have any questions.

**Comment by semenInRussia** [comment]
Thanks!
